<?php

namespace EspritApiBundle\Repository;

/**
 * produitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSearch($search)
    {
      $query =$this->createQueryBuilder('p')
      ->where('p.prixr <= :prixr')
      ->setParameter('prixr', $search.'%')
      ->orderBy('p.prixr' , 'ASC' )
      ->getQuery();
      return $query->getResult();
     
      }

}
